# Generated by Django 3.2 on 2023-08-22 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 13, 57, 4, 609777, tzinfo=utc))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
